version: '3.8'

services:
  typesense:
    image: typesense/typesense:0.24.1
    container_name: typesense
    restart: unless-stopped
    ports:
      - "8108:8108"
    volumes:
      - ./typesense_data:/data
    environment:
      - TYPESENSE_API_KEY=${API_KEY}
      - TYPESENSE_DATA_DIR="/data"
      - TYPESENSE_ENABLE_CORS="true"

volumes:
  typesense_data:
    driver: local

networks:
  airflow-networks:
    external: true
    name: airflow-networks